# マウス有効
set -g mouse on

# 履歴を増やす
set -g history-limit 100000

# Prefix + r で設定リロード
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# true color
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
